"""add is_active flag to button model

Revision ID: 5f04c9a0e7df
Revises: 7cf22ba41a9f
Create Date: 2025-07-19 22:17:27.592396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f04c9a0e7df'
down_revision: Union[str, Sequence[str], None] = '7cf22ba41a9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('button', sa.Column('is_active', sa.Boolean(), server_default='True', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('button', 'is_active')
    # ### end Alembic commands ###
