"""Add ondelete cascade to button foreign keys

Revision ID: 6be12ba7d331
Revises: d8ce81811dbb
Create Date: 2025-07-14 20:18:54.501074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6be12ba7d331'
down_revision: Union[str, Sequence[str], None] = 'd8ce81811dbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('button_source_node_id_fkey'), 'button', type_='foreignkey')
    op.drop_constraint(op.f('button_target_node_id_fkey'), 'button', type_='foreignkey')
    op.create_foreign_key(None, 'button', 'node', ['target_node_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'button', 'node', ['source_node_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'button', type_='foreignkey')
    op.drop_constraint(None, 'button', type_='foreignkey')
    op.create_foreign_key(op.f('button_target_node_id_fkey'), 'button', 'node', ['target_node_id'], ['id'])
    op.create_foreign_key(op.f('button_source_node_id_fkey'), 'button', 'node', ['source_node_id'], ['id'])
    # ### end Alembic commands ###
