"""First migration

Revision ID: 70cffe1273b2
Revises:
Create Date: 2025-07-12 15:51:52.899308

"""
from typing import Any, Sequence, Union

from alembic import op
from fastapi_storages.integrations.sqlalchemy import FileType as _FileType
from fastapi_storages import FileSystemStorage
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


class FileType(_FileType):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(storage=FileSystemStorage(path='/tmp'), *args, **kwargs)


# revision identifiers, used by Alembic.
revision: str = '70cffe1273b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('layout_type', postgresql.ENUM('text', 'text_image', 'gallery', name='layout_type_enum'), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', postgresql.ENUM('ADMIN', 'MANAGER', 'USER', name='user_roles_enum'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('button',
    sa.Column('source_node_id', sa.Integer(), nullable=True),
    sa.Column('target_node_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('source_node_id <> target_node_id', name='ck_button_no_self_link'),
    sa.ForeignKeyConstraint(['source_node_id'], ['node.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_node_id', 'order', name='uq_button_source_node_order'),
    sa.UniqueConstraint('source_node_id', 'target_node_id', name='uq_button_src_tgt')
    )
    op.create_index(op.f('ix_button_source_node_id'), 'button', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_button_target_node_id'), 'button', ['target_node_id'], unique=False)
    op.create_table('hrrequest',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', postgresql.ENUM('NEW', 'ANSWERED', name='hr_request_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('hr_reply', sa.Text(), nullable=True),
    sa.Column('replied_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('image_url', FileType(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'image_url', name='uq_image_node_image_url'),
    sa.UniqueConstraint('node_id', 'order', name='uq_image_node_order')
    )
    op.create_index(op.f('ix_image_file_name'), 'image', ['file_name'], unique=False)
    op.create_index(op.f('ix_image_node_id'), 'image', ['node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_node_id'), table_name='image')
    op.drop_index(op.f('ix_image_file_name'), table_name='image')
    op.drop_table('image')
    op.drop_table('hrrequest')
    op.drop_index(op.f('ix_button_target_node_id'), table_name='button')
    op.drop_index(op.f('ix_button_source_node_id'), table_name='button')
    op.drop_table('button')
    op.drop_table('user')
    op.drop_table('node')
    # ### end Alembic commands ###
