"""add is_active flag to node model

Revision ID: 7cf22ba41a9f
Revises: 6be12ba7d331
Create Date: 2025-07-19 18:25:47.375546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cf22ba41a9f'
down_revision: Union[str, Sequence[str], None] = '6be12ba7d331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('node', sa.Column('is_active', sa.Boolean(), server_default='True', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('node', 'is_active')
    # ### end Alembic commands ###
