"""add unique constraint to node.title

Revision ID: d8ce81811dbb
Revises: 70cffe1273b2
Create Date: 2025-07-14 18:57:09.464128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8ce81811dbb'
down_revision: Union[str, Sequence[str], None] = '70cffe1273b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'node', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'node', type_='unique')
    # ### end Alembic commands ###
