# Auth
MIN_PASSWORD_LEN = 4
JWT_LIFETIME = 7200

# Admin
DATE_TIME_FORMAT = '%Y-%m-%d %H:%M'
GALLERY_IMAGE_NUM = 10
MESSAGE_REPR_LEN = 20
TEXT_IMAGE_NUM = 1

# Hr_request params
HR_REQUEST_OFFSET = 0
HR_REQUEST_LIMIT = 5
